// apps/solid-mfe/src/App.tsx
import {createSignal, onCleanup} from "solid-js";
import logoImage from '../assets/images/solidjs.jpg';

const App = () => {
    const [title, setTitle] = createSignal("Solid MFE.");

    return (
        <div>
            <p>{title}</p>
            <img width={180} src={logoImage} alt="solidjs"/>
        </div>
    );
};

export default App;

// apps/vue-mfe/src/App.vue
<template>
  <div class="vue-mfe">
    <p>{{title}}</p>
    <img width="300" src="../assets/images/vue.jpg" alt="">
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue';

  export default defineComponent({
    data() {
      return {
        title: 'Vue MFE.',
      }
    },
  });
</script>

<style scoped lang="scss">
</style>
