// apps/lit-mfe/src/App.ts
import {LitElement, html, css} from 'lit';
import {customElement} from 'lit/decorators.js';
import logoImg from '../assets/images/lit.png';

@customElement('lit-app')
class App extends LitElement {
  static styles = css`
      p {
        color: green;
        margin: 0;
      }
    `;
  render(){
    return html`<div>
      <p>Lit Mfe.</p>
      <img width="300" src=${logoImg} alt="">
    </div>`;
  }
}

// apps/preact-mfe/src/App.tsx
import {Component, h} from 'preact';
import logoImage from '../assets/images/preact.png';

interface Props {
}

class App extends Component<Props> {
  render() {
    return (
      <div>
        <p>Preact MFE.</p>
        <img width={150} src={logoImage} alt="preact"/>
      </div>
    );
  }
}

export default App;
