// apps/preact-mfe/src/App.tsx
import {Component, h} from 'preact';
import logoImage from '../assets/images/preact.png';

interface Props {
}

class App extends Component<Props> {
  render() {
    return (
      <div>
        <p>Preact MFE.</p>
        <img width={150} src={logoImage} alt="preact"/>
      </div>
    );
  }
}

export default App;

// apps/solid-mfe/src/App.tsx
import {createSignal, onCleanup} from "solid-js";
import logoImage from '../assets/images/solidjs.jpg';

const App = () => {
    const [title, setTitle] = createSignal("Solid MFE.");

    return (
        <div>
            <p>{title}</p>
            <img width={180} src={logoImage} alt="solidjs"/>
        </div>
    );
};

export default App;
